import type { Ipo } from './types';

export const ipos: Ipo[] = [
  {
    id: 'aurora-innovations',
    companyName: 'Aurora Innovations',
    symbol: 'AURA',
    logoUrl: 'https://picsum.photos/seed/aurora/100/100',
    market: 'NASDAQ',
    ipoDate: '2024-09-15',
    priceRange: [22, 25],
    sharesOffered: 15000000,
    dealSize: 352500000,
    description: 'A cutting-edge AI research company specializing in large language models and generative art.',
    industry: 'Artificial Intelligence',
    predictionScore: 88,
    successProbability: 92,
    expectedReturn: 35.5,
    shapExplanations: {
      'Market Hype': 0.35,
      'Strong Financials': 0.25,
      'Experienced Leadership': 0.2,
      'Competitive Landscape': -0.05,
      'Regulatory Risk': -0.1,
      'Technology Scalability': 0.15,
    },
  },
  {
    id: 'zephyr-technologies',
    companyName: 'Zephyr Technologies',
    symbol: 'ZPHYR',
    logoUrl: 'https://picsum.photos/seed/zephyr/100/100',
    market: 'NYSE',
    ipoDate: '2024-09-20',
    priceRange: [18, 20],
    sharesOffered: 20000000,
    dealSize: 380000000,
    description: 'A leading provider of cloud infrastructure and enterprise software solutions, focusing on scalability and security.',
    industry: 'Cloud Computing',
    predictionScore: 76,
    successProbability: 85,
    expectedReturn: 22.0,
    shapExplanations: {
      'Recurring Revenue Model': 0.4,
      'Market Growth': 0.2,
      'Customer Retention': 0.15,
      'High Valuation': -0.15,
      'Technical Debt': -0.05,
    },
  },
  {
    id: 'nebula-dynamics',
    companyName: 'Nebula Dynamics',
    symbol: 'NBDY',
    logoUrl: 'https://picsum.photos/seed/nebula/100/100',
    market: 'NASDAQ',
    ipoDate: '2024-10-05',
    priceRange: [30, 35],
    sharesOffered: 10000000,
    dealSize: 325000000,
    description: 'A pioneer in commercial space exploration and satellite deployment technology.',
    industry: 'Aerospace & Defense',
    predictionScore: 68,
    successProbability: 75,
    expectedReturn: 15.8,
    shapExplanations: {
      'Government Contracts': 0.3,
      'Innovative Technology': 0.25,
      'High Capital Expenditure': -0.2,
      'Geopolitical Factors': -0.1,
      'Long-term Vision': 0.15,
    },
  },
  {
    id: 'cascade-biotherapeutics',
    companyName: 'Cascade Biotherapeutics',
    symbol: 'CBIO',
    logoUrl: 'https://picsum.photos/seed/cascade/100/100',
    market: 'NASDAQ',
    ipoDate: '2024-10-12',
    priceRange: [14, 16],
    sharesOffered: 25000000,
    dealSize: 375000000,
    description: 'A clinical-stage biotechnology company developing novel gene therapies for rare genetic disorders.',
    industry: 'Biotechnology',
    predictionScore: 45,
    successProbability: 55,
    expectedReturn: -5.2,
    shapExplanations: {
      'Promising Pipeline': 0.3,
      'Large Addressable Market': 0.15,
      'Clinical Trial Risk': -0.35,
      'FDA Approval Uncertainty': -0.25,
      'Patent Portfolio': 0.1,
    },
  },
    {
    id: 'pinnacle-financials',
    companyName: 'Pinnacle Financials',
    symbol: 'PINN',
    logoUrl: 'https://picsum.photos/seed/pinnacle/100/100',
    market: 'NYSE',
    ipoDate: '2024-11-01',
    priceRange: [45, 50],
    sharesOffered: 30000000,
    dealSize: 1425000000,
    description: 'A disruptive fintech platform offering decentralized banking and investment services.',
    industry: 'Financial Technology',
    predictionScore: 82,
    successProbability: 88,
    expectedReturn: 28.3,
    shapExplanations: {
      'Disruptive Business Model': 0.4,
      'User Growth Rate': 0.3,
      'Regulatory Scrutiny': -0.15,
      'Cybersecurity Threats': -0.1,
      'Scalable Platform': 0.25,
    },
  },
];
