
import type { Ipo } from './types';

export const ipos: Ipo[] = [
  {
    id: 'physicswallah',
    companyName: 'PhysicsWallah',
    symbol: 'PW',
    logoUrl: 'https://picsum.photos/seed/pw/100/100',
    market: 'NSE',
    ipoDate: '2025-04-10', // Updated Date
    priceRange: [500, 525], // Revised Range
    sharesOffered: 38000000,
    dealSize: 19500000000,
    description: 'A leading ed-tech platform in India, providing affordable and comprehensive learning experiences for students preparing for competitive exams, now showing strong post-listing performance.',
    industry: 'Ed-Tech',
    predictionScore: 88, // Score revised based on performance
    successProbability: 92,
    expectedReturn: 45.0, // Updated return
    naturalLanguageExplanation: "PhysicsWallah's strong brand recognition and impressive user growth were key drivers for its high prediction score. Post-IPO, the stock has shown significant gains, validating the initial analysis despite a competitive market.",
    shapExplanations: {
      'Brand Recognition': 0.45,
      'Strong User Growth': 0.3,
      'Competitive Market': -0.1,
      'Profitability': 0.25, // Increased weight
    },
    newsSentiment: {
      aggregatedScore: 0.9,
      positiveHeadlines: [
        { source: 'Economic Times', title: 'PhysicsWallah makes stellar debut, lists at 50% premium' },
        { source: 'Business Standard', title: 'Ed-tech giant continues to report strong user base growth post-IPO' }
      ],
      negativeHeadlines: [
        { source: 'LiveMint', title: 'Analysts watch for sustained profitability in coming quarters' }
      ]
    },
    promoterHoldingPost: 60,
    revenueTtm: 9500000000,
    profitMargin: 18.0,
    roe: 32.0,
    debtToEquity: 0.15,
    qibSubscription: 210.0,
    niiSubscription: 140.0,
    retailSubscription: 65.0,
    gmp: 60,
  },
  {
    id: 'capillary-technologies',
    companyName: 'Capillary Technologies India',
    symbol: 'CAPTECH',
    logoUrl: 'https://picsum.photos/seed/capillary/100/100',
    market: 'BSE',
    ipoDate: '2025-05-15', // Updated Date
    priceRange: [410, 430], // Revised Range
    sharesOffered: 24000000,
    dealSize: 10100000000,
    description: 'A global leader in customer loyalty and engagement solutions, demonstrating stable growth and market expansion since its public listing.',
    industry: 'Software as a Service (SaaS)',
    predictionScore: 81, // Revised score
    successProbability: 88,
    expectedReturn: 32.5, // Updated return
    naturalLanguageExplanation: "Capillary Technologies' predictable recurring revenue and market leadership were strong positive factors in its successful IPO. The company is actively mitigating client concentration risk by expanding its customer base.",
    shapExplanations: {
      'Recurring Revenue Model': 0.4,
      'Global Presence': 0.25,
      'Client Concentration Risk': -0.1, // Reduced risk
      'High Valuation': -0.1,
      'Market Leadership': 0.25,
    },
     newsSentiment: {
      aggregatedScore: 0.75,
      positiveHeadlines: [
        { source: 'VC Circle', title: 'Capillary Tech lists at a healthy premium, SaaS story strong' },
        { source: 'YourStory', title: 'Capillary announces two new enterprise clients post-IPO' }
      ],
      negativeHeadlines: [
        { source: 'Reuters', title: 'Valuation remains a key metric for investors to watch' }
      ]
    },
    promoterHoldingPost: 65,
    revenueTtm: 6000000000,
    profitMargin: 14.0,
    roe: 24.0,
    debtToEquity: 0.3,
    qibSubscription: 160.0,
    niiSubscription: 110.0,
    retailSubscription: 40.0,
    gmp: 40,
  },
  {
    id: 'emmvee-photovoltaic',
    companyName: 'Emmvee Photovoltaic Power',
    symbol: 'EMMVEE',
    logoUrl: 'https://picsum.photos/seed/emmvee/100/100',
    market: 'NSE',
    ipoDate: '2024-11-18',
    priceRange: [220, 230],
    sharesOffered: 50000000,
    dealSize: 11250000000,
    description: 'A prominent manufacturer of solar water heating systems and solar photovoltaic modules.',
    industry: 'Renewable Energy',
    predictionScore: 72,
    successProbability: 80,
    expectedReturn: 25.5,
    naturalLanguageExplanation: "Favorable government incentives in the renewable sector and rising energy demand are major tailwinds for Emmvee. The key risks hinge on volatile raw material costs and increasing competition from cheaper imports.",
    shapExplanations: {
      'Government Incentives': 0.3,
      'Rising Energy Demand': 0.25,
      'Raw Material Costs': -0.2,
      'Competition from Imports': -0.1,
      'Strong Order Book': 0.15,
    },
    newsSentiment: {
      aggregatedScore: 0.70,
      positiveHeadlines: [
        { source: 'Economic Times', title: 'PLI scheme boosts Emmvee manufacturing plans' }
      ],
      negativeHeadlines: [
        { source: 'PV Magazine', title: 'Solar module prices remain volatile amid supply chain issues' }
      ]
    },
    promoterHoldingPost: 70,
    revenueTtm: 15000000000,
    profitMargin: 8.0,
    roe: 18.5,
    debtToEquity: 0.8,
    qibSubscription: 110.0,
    niiSubscription: 70.0,
    retailSubscription: 25.0,
    gmp: 28,
  },
  {
    id: 'sudeep-pharma',
    companyName: 'Sudeep Pharma',
    symbol: 'SUDEEP',
    logoUrl: 'https://picsum.photos/seed/sudeep/100/100',
    market: 'BSE',
    ipoDate: '2024-12-09',
    priceRange: [300, 315],
    sharesOffered: 15000000,
    dealSize: 4612500000,
    description: 'A specialized manufacturer of mineral-based excipients for the pharmaceutical industry.',
    industry: 'Pharmaceuticals',
    predictionScore: 68,
    successProbability: 75,
    expectedReturn: 18.0,
    naturalLanguageExplanation: "Sudeep Pharma's outlook is supported by its niche market position and consistent financial performance. The main risks to consider are its dependency on a few key clients and the stringent regulatory environment.",
    shapExplanations: {
      'Niche Market Position': 0.3,
      'Strong Client Relationships': 0.2,
      'Regulatory Compliance': -0.15,
      'Dependency on Key Clients': -0.1,
      'Consistent Financials': 0.15,
    },
    newsSentiment: {
      aggregatedScore: 0.55,
      positiveHeadlines: [
        { source: 'PharmaBiz', title: 'Sudeep Pharma gets regulatory nod for new plant' }
      ],
      negativeHeadlines: []
    },
    promoterHoldingPost: 75,
    revenueTtm: 7000000000,
    profitMargin: 18.0,
    roe: 22.0,
    debtToEquity: 0.5,
    qibSubscription: 95.0,
    niiSubscription: 60.0,
    retailSubscription: 20.0,
    gmp: 22,
  },
  {
    id: 'tenneco-clean-air',
    companyName: 'Tenneco Clean Air India',
    symbol: 'TENNECO',
    logoUrl: 'https://picsum.photos/seed/tenneco/100/100',
    market: 'NSE',
    ipoDate: '2025-01-10',
    priceRange: [600, 625],
    sharesOffered: 12000000,
    dealSize: 7350000000,
    description: 'A leading manufacturer and supplier of clean air solutions for the automotive industry, focusing on emission control systems.',
    industry: 'Automotive Components',
    predictionScore: 75,
    successProbability: 82,
    expectedReturn: 20.0,
    naturalLanguageExplanation: "Tenneco's prospects are strongly tied to the implementation of stricter emission norms and its established brand. However, the cyclical nature of the auto industry and the long-term transition to EVs are factors to watch.",
    shapExplanations: {
      'Stricter Emission Norms': 0.35,
      'Strong OEM Relationships': 0.25,
      'Cyclical Auto Industry': -0.15,
      'EV Transition Risk': -0.1,
      'Established Brand': 0.2,
    },
    promoterHoldingPost: 55,
    revenueTtm: 20000000000,
    profitMargin: 9.5,
    roe: 19.5,
    debtToEquity: 0.6,
    qibSubscription: 120.0,
    niiSubscription: 80.0,
    retailSubscription: 40.0,
    gmp: 25,
  },
  {
    id: 'excelsoft-technologies',
    companyName: 'Excelsoft Technologies',
    symbol: 'EXCELSOFT',
    logoUrl: 'https://picsum.photos/seed/excelsoft/100/100',
    market: 'BSE',
    ipoDate: '2025-01-20',
    priceRange: [150, 160],
    sharesOffered: 20000000,
    dealSize: 3100000000,
    description: 'A provider of technology-based solutions for the education and training sectors.',
    industry: 'Ed-Tech',
    predictionScore: 65,
    successProbability: 70,
    expectedReturn: 15.0,
    naturalLanguageExplanation: 'Growth in digital learning and a diverse product portfolio are positive signals for Excelsoft. The score is tempered by intense competition and relatively low profit margins common in the sector.',
    shapExplanations: {
      'Growing Digital Learning': 0.3,
      'Diverse Product Portfolio': 0.2,
      'Intense Competition': -0.2,
      'Low Margin Business': -0.1,
      'Experienced Management': 0.1,
    },
    promoterHoldingPost: 68,
    revenueTtm: 3000000000,
    profitMargin: 7.0,
    roe: 15.0,
    debtToEquity: 0.3,
    qibSubscription: 80.0,
    niiSubscription: 50.0,
    retailSubscription: 15.0,
    gmp: 18,
  },
  {
    id: 'fujiyama-power-systems',
    companyName: 'Fujiyama Power Systems',
    symbol: 'FUJIYAMA',
    logoUrl: 'https://picsum.photos/seed/fujiyama/100/100',
    market: 'NSE',
    ipoDate: '2025-02-05',
    priceRange: [180, 190],
    sharesOffered: 10000000,
    dealSize: 1850000000,
    description: 'A company engaged in manufacturing and marketing of batteries for various applications including solar and electric vehicles.',
    industry: 'Electrical Equipment',
    predictionScore: 62,
    successProbability: 68,
    expectedReturn: 12.0,
    naturalLanguageExplanation: 'Fujiyama is well-positioned to benefit from growth in the EV and solar sectors. However, the risk of technology obsolescence and raw material price volatility are significant concerns that temper the outlook.',
    shapExplanations: {
      'EV and Solar Growth': 0.35,
      'Make in India Initiative': 0.2,
      'Technology Obsolescence': -0.25,
      'Price Volatility': -0.15,
      'Distribution Network': 0.1,
    },
    promoterHoldingPost: 72,
    revenueTtm: 2500000000,
    profitMargin: 6.5,
    roe: 14.0,
    debtToEquity: 0.9,
    qibSubscription: 70.0,
    niiSubscription: 45.0,
    retailSubscription: 22.0,
    gmp: 15,
  },
   {
    id: 'ola-electric',
    companyName: 'Ola Electric',
    symbol: 'OLAELECT',
    logoUrl: 'https://picsum.photos/seed/ola/100/100',
    market: 'NSE',
    ipoDate: '2025-02-15',
    priceRange: [1200, 1250],
    sharesOffered: 50000000,
    dealSize: 61250000000,
    description: 'A leading electric vehicle company in India, known for its electric scooters and ambitions in battery technology.',
    industry: 'Automotive (EV)',
    predictionScore: 88,
    successProbability: 92,
    expectedReturn: 55.0,
    naturalLanguageExplanation: "Ola Electric's dominant market leadership and strong brand are powerful drivers for its high score. The primary risks are its significant cash burn rate and potential supply chain disruptions, which are common in the fast-growing EV industry.",
    shapExplanations: {
      'Market Leadership in EV': 0.45,
      'Strong Brand Following': 0.3,
      'High Cash Burn Rate': -0.2,
      'Supply Chain Risks': -0.1,
      'Vertical Integration (Battery)': 0.25,
    },
    promoterHoldingPost: 45,
    revenueTtm: 27000000000,
    profitMargin: -25.0, // Still loss-making
    roe: -40.0,
    debtToEquity: 1.5,
    qibSubscription: 250.0,
    niiSubscription: 200.0,
    retailSubscription: 80.0,
    gmp: 60,
  },
  {
    id: 'swiggy',
    companyName: 'Swiggy',
    symbol: 'SWIGGY',
    logoUrl: 'https://picsum.photos/seed/swiggy/100/100',
    market: 'BSE',
    ipoDate: '2025-03-01',
    priceRange: [750, 800],
    sharesOffered: 80000000,
    dealSize: 62000000000,
    description: 'A dominant player in Indias food delivery and quick commerce space, offering a wide range of services from restaurants to grocery delivery.',
    industry: 'Consumer Tech / Logistics',
    predictionScore: 82,
    successProbability: 88,
    expectedReturn: 35.0,
    naturalLanguageExplanation: "Swiggy's strong position in a duopoly market and its successful diversification into quick commerce are major strengths. The company's path to profitability remains a key concern for investors, alongside intense competition.",
    shapExplanations: {
      'Market Duopoly': 0.4,
      'Diversified Services': 0.3,
      'Path to Profitability': -0.15,
      'Intense Competition': -0.1,
      'User Base Growth': 0.2,
    },
    promoterHoldingPost: 40,
    revenueTtm: 85000000000,
    profitMargin: -10.0,
    roe: -30.0,
    debtToEquity: 0.7,
    qibSubscription: 180.0,
    niiSubscription: 150.0,
    retailSubscription: 60.0,
    gmp: 45,
  },
  {
    id: 'firstcry',
    companyName: 'FirstCry',
    symbol: 'FIRSTCRY',
    logoUrl: 'https://picsum.photos/seed/firstcry/100/100',
    market: 'NSE',
    ipoDate: '2025-03-20',
    priceRange: [500, 525],
    sharesOffered: 35000000,
    dealSize: 18000000000,
    description: 'Indias largest omnichannel platform for maternity, baby, and kids products, with a strong online and offline presence.',
    industry: 'E-commerce / Retail',
    predictionScore: 76,
    successProbability: 80,
    expectedReturn: 22.0,
    naturalLanguageExplanation: 'FirstCry benefits greatly from its unique omnichannel strategy and strong brand loyalty in a niche market. The model sees some risk associated with complex inventory management and the mixed post-IPO performance of similar e-commerce peers.',
    shapExplanations: {
      'Omnichannel Strategy': 0.35,
      'Market Leadership': 0.25,
      'Complex Inventory': -0.1,
      'Post-IPO Performance of Peers': -0.05,
      'Brand Loyalty': 0.2,
    },
    promoterHoldingPost: 50,
    revenueTtm: 56000000000,
    profitMargin: 2.5,
    roe: 10.0,
    debtToEquity: 0.4,
    qibSubscription: 110.0,
    niiSubscription: 85.0,
    retailSubscription: 35.0,
    gmp: 30,
  },
  {
    id: 'meesho',
    companyName: 'Meesho',
    symbol: 'MEESHO',
    logoUrl: 'https://picsum.photos/seed/meesho/100/100',
    market: 'Mainboard',
    ipoDate: '2025-12-03',
    priceRange: [480, 500],
    sharesOffered: 90000000,
    dealSize: 44100000000,
    description: 'A pioneering social commerce platform in India, enabling individuals and small businesses to start their online stores via social channels.',
    industry: 'E-commerce',
    predictionScore: 79,
    successProbability: 85,
    expectedReturn: 30.0,
    naturalLanguageExplanation: 'Meesho has a massive user base and a unique business model targeting Tier-2 and Tier-3 cities, which is a major strength. However, the path to profitability and high cash burn are significant risks that investors will be scrutinizing.',
    shapExplanations: {
      'Large Addressable Market': 0.4,
      'Asset-Light Model': 0.25,
      'Path to Profitability': -0.2,
      'Intense Competition': -0.15,
      'Strong User Growth': 0.3,
    },
    newsSentiment: {
      aggregatedScore: 0.7,
      positiveHeadlines: [
        { source: 'Economic Times', title: 'Meesho narrows losses, prepares for blockbuster IPO' },
        { source: 'YourStory', title: 'Social commerce giant eyes profitability ahead of public listing' }
      ],
      negativeHeadlines: [
        { source: 'LiveMint', title: 'Competition heats up in social commerce space' }
      ]
    },
    promoterHoldingPost: 35,
    revenueTtm: 80000000000,
    profitMargin: -15.0,
    roe: -35.0,
    debtToEquity: 0.5,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'aequs',
    companyName: 'Aequs',
    symbol: 'AEQUS',
    logoUrl: 'https://picsum.photos/seed/aequs/100/100',
    market: 'Mainboard',
    ipoDate: '2025-12-03',
    priceRange: [300, 320],
    sharesOffered: 25000000,
    dealSize: 7750000000,
    description: 'A diversified contract manufacturing company with capabilities in aerospace, automotive, and toys.',
    industry: 'Contract Manufacturing',
    predictionScore: 70,
    successProbability: 75,
    expectedReturn: 15.0,
    naturalLanguageExplanation: 'Aequs has a diverse business model, reducing dependency on any one sector. The aerospace division shows high growth potential. Risks include high capital expenditure and global supply chain disruptions.',
    shapExplanations: {
      'Diversified Business': 0.3,
      'Aerospace Growth': 0.25,
      'High Capex': -0.15,
      'Supply Chain Risk': -0.1
    },
    promoterHoldingPost: 65,
    revenueTtm: 25000000000,
    profitMargin: 8.0,
    roe: 15.0,
    debtToEquity: 1.2,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'vidya-wires',
    companyName: 'Vidya Wires',
    symbol: 'VIDYA',
    logoUrl: 'https://picsum.photos/seed/vidya/100/100',
    market: 'Mainboard',
    ipoDate: '2025-12-03',
    priceRange: [200, 210],
    sharesOffered: 10000000,
    dealSize: 2050000000,
    description: 'A manufacturer of copper and aluminum winding wires used in transformers, motors, and generators.',
    industry: 'Industrial Goods',
    predictionScore: 65,
    successProbability: 70,
    expectedReturn: 12.0,
    naturalLanguageExplanation: 'Vidya Wires is set to benefit from infrastructure and power sector growth. The company has stable financials but faces risks from commodity price fluctuations.',
    shapExplanations: {
      'Infra Growth': 0.3,
      'Stable Financials': 0.2,
      'Commodity Price Risk': -0.2
    },
    promoterHoldingPost: 70,
    revenueTtm: 5000000000,
    profitMargin: 10.0,
    roe: 18.0,
    debtToEquity: 0.6,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'wakefit-innovations',
    companyName: 'Wakefit Innovations',
    symbol: 'WAKEFIT',
    logoUrl: 'https://picsum.photos/seed/wakefit/100/100',
    market: 'Mainboard',
    ipoDate: '2025-12-08',
    priceRange: [1800, 1850],
    sharesOffered: 15000000,
    dealSize: 27375000000,
    description: 'A leading direct-to-consumer brand for sleep and home solutions, including mattresses, pillows, and furniture.',
    industry: 'D2C / Retail',
    predictionScore: 78,
    successProbability: 82,
    expectedReturn: 25.0,
    naturalLanguageExplanation: 'Wakefit has a strong brand in the online space and has successfully expanded into home furniture. High marketing spend and competition from unorganized sector are key risks.',
    shapExplanations: {
      'Strong D2C Brand': 0.4,
      'Category Expansion': 0.2,
      'High Marketing Spend': -0.15,
      'Competition': -0.1,
    },
    promoterHoldingPost: 55,
    revenueTtm: 10000000000,
    profitMargin: 5.0,
    roe: 12.0,
    debtToEquity: 0.4,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'corona-remedies',
    companyName: 'Corona Remedies',
    symbol: 'CORONA',
    logoUrl: 'https://picsum.photos/seed/corona/100/100',
    market: 'Mainboard',
    ipoDate: '2025-12-08',
    priceRange: [650, 680],
    sharesOffered: 18000000,
    dealSize: 12000000000,
    description: 'A fast-growing pharmaceutical company with a strong presence in the Indian domestic market, focusing on therapeutic areas like cardiology, diabetes, and gynecology.',
    industry: 'Pharmaceuticals',
    predictionScore: 74,
    successProbability: 80,
    expectedReturn: 22.0,
    naturalLanguageExplanation: 'Corona Remedies has shown robust revenue growth and has a strong portfolio of brands in high-growth therapeutic areas. The primary risks are its high dependence on the Indian market and ongoing regulatory scrutiny common to the pharma sector.',
    shapExplanations: {
      'Strong Revenue Growth': 0.35,
      'Brand Portfolio': 0.3,
      'Domestic Market Dependence': -0.15,
      'Regulatory Environment': -0.1,
      'Experienced Management': 0.15,
    },
    promoterHoldingPost: 78,
    revenueTtm: 9000000000,
    profitMargin: 20.0,
    roe: 25.0,
    debtToEquity: 0.4,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'park-medi-world',
    companyName: 'Park Medi World',
    symbol: 'PARKMED',
    logoUrl: 'https://picsum.photos/seed/parkmedi/100/100',
    market: 'Mainboard/SME',
    ipoDate: '2025-12-10',
    priceRange: [140, 150],
    sharesOffered: 5000000,
    dealSize: 725000000,
    description: 'Operates a chain of pharmacies and provides diagnostic services in Tier-2 and Tier-3 cities.',
    industry: 'Healthcare / Retail',
    predictionScore: 68,
    successProbability: 72,
    expectedReturn: 18.0,
    naturalLanguageExplanation: 'Focus on underserved markets provides a good growth runway. Smaller scale and competition from online pharmacies are potential challenges.',
    shapExplanations: {
      'Tier-2/3 Focus': 0.3,
      'Integrated Model': 0.2,
      'Competition': -0.15,
      'Scale of Operations': -0.1
    },
    promoterHoldingPost: 75,
    revenueTtm: 1500000000,
    profitMargin: 8.0,
    roe: 16.0,
    debtToEquity: 0.7,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'nephrocare-health',
    companyName: 'Nephrocare Health Services',
    symbol: 'NEPHRO',
    logoUrl: 'https://picsum.photos/seed/nephro/100/100',
    market: 'Mainboard/SME',
    ipoDate: '2025-12-10',
    priceRange: [400, 420],
    sharesOffered: 8000000,
    dealSize: 3280000000,
    description: 'A provider of dialysis care services through a network of standalone centers.',
    industry: 'Healthcare Services',
    predictionScore: 72,
    successProbability: 78,
    expectedReturn: 20.0,
    naturalLanguageExplanation: 'Rising incidence of kidney diseases and an asset-light model are key positives. High reliance on government healthcare schemes for revenue could be a risk.',
    shapExplanations: {
      'Healthcare Demand': 0.35,
      'Asset-Light Model': 0.25,
      'Govt Scheme Reliance': -0.2,
    },
    promoterHoldingPost: 60,
    revenueTtm: 4000000000,
    profitMargin: 12.0,
    roe: 20.0,
    debtToEquity: 0.5,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'clear-secured-services',
    companyName: 'Clear Secured Services',
    symbol: 'CLEARSEC',
    logoUrl: 'https://picsum.photos/seed/clearsec/100/100',
    market: 'SME',
    ipoDate: '2025-12-01',
    priceRange: [80, 85],
    sharesOffered: 3000000,
    dealSize: 247500000,
    description: 'Provides security personnel and facility management services to corporate clients.',
    industry: 'Services',
    predictionScore: 60,
    successProbability: 65,
    expectedReturn: 10.0,
    naturalLanguageExplanation: 'A high-volume, low-margin business with stable demand. Faces high employee attrition and intense competition.',
    shapExplanations: {
      'Stable Demand': 0.2,
      'High Attrition': -0.2,
      'Low Margins': -0.15,
    },
    promoterHoldingPost: 73,
    revenueTtm: 800000000,
    profitMargin: 5.0,
    roe: 14.0,
    debtToEquity: 0.3,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'speb-adhesives',
    companyName: 'SPEB Adhesives',
    symbol: 'SPEB',
    logoUrl: 'https://picsum.photos/seed/speb/100/100',
    market: 'SME',
    ipoDate: '2025-12-01',
    priceRange: [110, 115],
    sharesOffered: 2000000,
    dealSize: 225000000,
    description: 'Manufacturer of industrial adhesives and sealants for various industries like footwear, automotive, and construction.',
    industry: 'Chemicals',
    predictionScore: 64,
    successProbability: 68,
    expectedReturn: 14.0,
    naturalLanguageExplanation: 'B2B business model with diversified client base. Susceptible to chemical raw material price volatility.',
    shapExplanations: {
      'B2B Model': 0.25,
      'Client Diversification': 0.2,
      'Raw Material Volatility': -0.2,
    },
    promoterHoldingPost: 74,
    revenueTtm: 500000000,
    profitMargin: 9.0,
    roe: 17.0,
    debtToEquity: 0.8,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'invicta-diagnostic',
    companyName: 'Invicta Diagnostic',
    symbol: 'INVICTA',
    logoUrl: 'https://picsum.photos/seed/invicta/100/100',
    market: 'SME',
    ipoDate: '2025-12-01',
    priceRange: [120, 125],
    sharesOffered: 4000000,
    dealSize: 490000000,
    description: 'A chain of diagnostic imaging centers offering MRI, CT Scan, and other radiology services.',
    industry: 'Healthcare Services',
    predictionScore: 67,
    successProbability: 72,
    expectedReturn: 16.0,
    naturalLanguageExplanation: 'Capital-intensive business but high growth potential due to increasing healthcare awareness. Competition from hospital chains is a key factor.',
    shapExplanations: {
      'Growth Potential': 0.3,
      'High Entry Barrier': 0.25,
      'Competition': -0.15,
      'High Capex': -0.1,
    },
    promoterHoldingPost: 68,
    revenueTtm: 1000000000,
    profitMargin: 15.0,
    roe: 21.0,
    debtToEquity: 1.1,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'neochem-bio-solutions',
    companyName: 'Neochem Bio Solutions',
    symbol: 'NEOCHEM',
    logoUrl: 'https://picsum.photos/seed/neochem/100/100',
    market: 'SME',
    ipoDate: '2025-12-02',
    priceRange: [90, 95],
    sharesOffered: 2500000,
    dealSize: 231250000,
    description: 'Manufacturer of specialty biochemicals and enzymes for industrial applications.',
    industry: 'Chemicals',
    predictionScore: 66,
    successProbability: 70,
    expectedReturn: 15.0,
    naturalLanguageExplanation: 'Niche business with high-margin products. The business is R&D intensive and requires continuous innovation.',
    shapExplanations: {
      'Niche Products': 0.3,
      'High Margins': 0.25,
      'R&D Intensive': -0.15,
    },
    promoterHoldingPost: 72,
    revenueTtm: 600000000,
    profitMargin: 18.0,
    roe: 22.0,
    debtToEquity: 0.4,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'helloji-holidays',
    companyName: 'Helloji Holidays',
    symbol: 'HELLOJI',
    logoUrl: 'https://picsum.photos/seed/helloji/100/100',
    market: 'SME',
    ipoDate: '2025-12-02',
    priceRange: [75, 80],
    sharesOffered: 1500000,
    dealSize: 116250000,
    description: 'A travel and tourism company specializing in customized holiday packages.',
    industry: 'Travel & Tourism',
    predictionScore: 58,
    successProbability: 62,
    expectedReturn: 8.0,
    naturalLanguageExplanation: 'The travel industry is recovering, but this is a highly competitive and low-margin business, sensitive to economic downturns.',
    shapExplanations: {
      'Travel Recovery': 0.25,
      'High Competition': -0.2,
      'Low Margins': -0.2,
    },
    promoterHoldingPost: 70,
    revenueTtm: 400000000,
    profitMargin: 4.0,
    roe: 10.0,
    debtToEquity: 0.9,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'shri-kanha-stainless',
    companyName: 'Shri Kanha Stainless',
    symbol: 'KANHA',
    logoUrl: 'https://picsum.photos/seed/kanha/100/100',
    market: 'SME',
    ipoDate: '2025-12-03',
    priceRange: [130, 135],
    sharesOffered: 3000000,
    dealSize: 400000000,
    description: 'Manufacturer of stainless steel pipes and tubes for industrial and decorative use.',
    industry: 'Metals',
    predictionScore: 63,
    successProbability: 67,
    expectedReturn: 13.0,
    naturalLanguageExplanation: 'Direct play on infrastructure and construction demand. Highly cyclical business exposed to raw material price fluctuations.',
    shapExplanations: {
      'Infra Demand': 0.3,
      'Cyclical Business': -0.15,
      'Metal Price Risk': -0.15,
    },
    promoterHoldingPost: 71,
    revenueTtm: 1200000000,
    profitMargin: 7.0,
    roe: 16.0,
    debtToEquity: 1.0,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'western-overseas',
    companyName: 'Western Overseas Study Abroad',
    symbol: 'WESTERN',
    logoUrl: 'https://picsum.photos/seed/western/100/100',
    market: 'SME',
    ipoDate: '2025-12-04',
    priceRange: [150, 160],
    sharesOffered: 2000000,
    dealSize: 310000000,
    description: 'Provides overseas education consultancy services to students.',
    industry: 'Education Services',
    predictionScore: 69,
    successProbability: 74,
    expectedReturn: 19.0,
    naturalLanguageExplanation: 'Growing trend of Indian students studying abroad is a major tailwind. Business is sensitive to changes in international visa policies.',
    shapExplanations: {
      'Study Abroad Trend': 0.4,
      'Visa Policy Risk': -0.2,
      'Fragmented Market': -0.1
    },
    promoterHoldingPost: 65,
    revenueTtm: 700000000,
    profitMargin: 20.0,
    roe: 25.0,
    debtToEquity: 0.2,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'luxury-time',
    companyName: 'Luxury Time',
    symbol: 'LUXTIME',
    logoUrl: 'https://picsum.photos/seed/luxtime/100/100',
    market: 'SME',
    ipoDate: '2025-12-04',
    priceRange: [250, 260],
    sharesOffered: 1000000,
    dealSize: 255000000,
    description: 'Retailer of high-end luxury watches from international brands.',
    industry: 'Luxury Retail',
    predictionScore: 71,
    successProbability: 76,
    expectedReturn: 21.0,
    naturalLanguageExplanation: 'Rising disposable income and aspiration for luxury goods are key growth drivers. High working capital requirements and reliance on brand partnerships are risks.',
    shapExplanations: {
      'Luxury Demand': 0.35,
      'High Margins': 0.25,
      'Working Capital': -0.15,
      'Brand Dependency': -0.1
    },
    promoterHoldingPost: 60,
    revenueTtm: 900000000,
    profitMargin: 15.0,
    roe: 24.0,
    debtToEquity: 0.5,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'encompass-design',
    companyName: 'Encompass Design India',
    symbol: 'ENCOMPASS',
    logoUrl: 'https://picsum.photos/seed/encompass/100/100',
    market: 'SME',
    ipoDate: '2025-12-05',
    priceRange: [100, 105],
    sharesOffered: 2000000,
    dealSize: 205000000,
    description: 'Provides interior design and turnkey project execution for commercial and residential spaces.',
    industry: 'Design & Construction',
    predictionScore: 62,
    successProbability: 66,
    expectedReturn: 11.0,
    naturalLanguageExplanation: 'Benefits from the real estate and construction boom. It is a very fragmented market and the business is project-based, leading to lumpy revenues.',
    shapExplanations: {
      'Real Estate Boom': 0.3,
      'Fragmented Market': -0.2,
      'Lumpy Revenue': -0.15
    },
    promoterHoldingPost: 70,
    revenueTtm: 500000000,
    profitMargin: 10.0,
    roe: 18.0,
    debtToEquity: 0.7,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'methodhub-software',
    companyName: 'Methodhub Software',
    symbol: 'METHODHUB',
    logoUrl: 'https://picsum.photos/seed/methodhub/100/100',
    market: 'SME',
    ipoDate: '2025-12-05',
    priceRange: [180, 190],
    sharesOffered: 1500000,
    dealSize: 277500000,
    description: 'An IT services company providing digital transformation and cloud services.',
    industry: 'IT Services',
    predictionScore: 68,
    successProbability: 73,
    expectedReturn: 17.0,
    naturalLanguageExplanation: 'Steady growth in IT spending is a positive. The company faces stiff competition and will need to manage employee costs and attrition.',
    shapExplanations: {
      'IT Spending Growth': 0.3,
      'Sticky Clients': 0.25,
      'Stiff Competition': -0.15,
      'Employee Attrition': -0.1
    },
    promoterHoldingPost: 68,
    revenueTtm: 800000000,
    profitMargin: 14.0,
    roe: 22.0,
    debtToEquity: 0.1,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'flywings-simulator',
    companyName: 'Flywings Simulator Training Centre',
    symbol: 'FLYWINGS',
    logoUrl: 'https://picsum.photos/seed/flywings/100/100',
    market: 'SME',
    ipoDate: '2025-12-05',
    priceRange: [200, 210],
    sharesOffered: 1000000,
    dealSize: 205000000,
    description: 'Operates aviation simulator training centers for pilots and cabin crew.',
    industry: 'Aviation Services',
    predictionScore: 70,
    successProbability: 75,
    expectedReturn: 20.0,
    naturalLanguageExplanation: 'Growing aviation market in India provides a clear growth path. High capex for simulators and dependency on aviation regulations are key risks.',
    shapExplanations: {
      'Aviation Growth': 0.4,
      'High Entry Barrier': 0.25,
      'Regulatory Risk': -0.15,
      'High Capex': -0.1,
    },
    promoterHoldingPost: 65,
    revenueTtm: 600000000,
    profitMargin: 25.0,
    roe: 28.0,
    debtToEquity: 1.0,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'prodocs-solutions',
    companyName: 'Prodocs Solutions',
    symbol: 'PRODOCS',
    logoUrl: 'https://picsum.photos/seed/prodocs/100/100',
    market: 'SME',
    ipoDate: '2025-12-08',
    priceRange: [95, 100],
    sharesOffered: 2000000,
    dealSize: 195000000,
    description: 'A provider of document management and digital archiving solutions.',
    industry: 'Software / IT Services',
    predictionScore: 65,
    successProbability: 69,
    expectedReturn: 14.0,
    naturalLanguageExplanation: 'Increasing digitization provides a steady demand for services. This is a competitive space with larger players also present.',
    shapExplanations: {
      'Digitization Trend': 0.3,
      'Recurring Revenue': 0.2,
      'Competition': -0.2,
    },
    promoterHoldingPost: 70,
    revenueTtm: 400000000,
    profitMargin: 12.0,
    roe: 19.0,
    debtToEquity: 0.3,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  },
  {
    id: 'unisem-agritech',
    companyName: 'Unisem Agritech',
    symbol: 'UNISEM',
    logoUrl: 'https://picsum.photos/seed/unisem/100/100',
    market: 'SME',
    ipoDate: '2025-12-10',
    priceRange: [110, 115],
    sharesOffered: 3000000,
    dealSize: 337500000,
    description: 'Develops and sells hybrid seeds for various crops.',
    industry: 'Agri-tech',
    predictionScore: 67,
    successProbability: 71,
    expectedReturn: 16.0,
    naturalLanguageExplanation: 'The business has a large addressable market in the agricultural sector. Performance is heavily dependent on monsoon cycles and government policies.',
    shapExplanations: {
      'Agri Sector': 0.3,
      'R&D Focus': 0.2,
      'Monsoon Dependency': -0.2,
      'Policy Risk': -0.1
    },
    promoterHoldingPost: 72,
    revenueTtm: 900000000,
    profitMargin: 11.0,
    roe: 18.0,
    debtToEquity: 0.6,
    qibSubscription: 0,
    niiSubscription: 0,
    retailSubscription: 0,
    gmp: 0,
  }
];
