import type { Ipo } from './types';

export const ipos: Ipo[] = [
  {
    id: 'physicswallah',
    companyName: 'PhysicsWallah',
    symbol: 'PW',
    logoUrl: 'https://picsum.photos/seed/pw/100/100',
    market: 'NSE',
    ipoDate: '2024-11-25',
    priceRange: [450, 475],
    sharesOffered: 40000000,
    dealSize: 18000000000,
    description: 'A leading ed-tech platform in India, providing affordable and comprehensive learning experiences for students preparing for competitive exams.',
    industry: 'Ed-Tech',
    predictionScore: 85,
    successProbability: 90,
    expectedReturn: 40.5,
    naturalLanguageExplanation: "PhysicsWallah's strong brand recognition and impressive user growth are key drivers for its high prediction score. While the competitive market poses a slight risk, its solid profitability makes it a compelling IPO.",
    shapExplanations: {
      'Brand Recognition': 0.4,
      'Strong User Growth': 0.3,
      'Competitive Market': -0.1,
      'Profitability': 0.2,
      'Regulatory Scrutiny': -0.05,
    },
    promoterHoldingPost: 60,
    revenueTtm: 8000000000,
    profitMargin: 15.0,
    roe: 28.0,
    debtToEquity: 0.2,
    qibSubscription: 180.0,
    niiSubscription: 120.0,
    retailSubscription: 50.0,
    gmp: 55,
  },
  {
    id: 'capillary-technologies',
    companyName: 'Capillary Technologies India',
    symbol: 'CAPTECH',
    logoUrl: 'https://picsum.photos/seed/capillary/100/100',
    market: 'BSE',
    ipoDate: '2024-12-02',
    priceRange: [380, 400],
    sharesOffered: 25000000,
    dealSize: 9750000000,
    description: 'A global leader in customer loyalty and engagement solutions, helping brands build strong relationships with their customers.',
    industry: 'Software as a Service (SaaS)',
    predictionScore: 78,
    successProbability: 85,
    expectedReturn: 28.0,
    naturalLanguageExplanation: "Capillary Technologies' predictable recurring revenue and established market leadership are strong positive factors. However, investors should note the high valuation and a concentration of revenue from a few large clients as potential risks.",
    shapExplanations: {
      'Recurring Revenue Model': 0.35,
      'Global Presence': 0.25,
      'Client Concentration Risk': -0.15,
      'High Valuation': -0.1,
      'Market Leadership': 0.2,
    },
    promoterHoldingPost: 65,
    revenueTtm: 5000000000,
    profitMargin: 12.5,
    roe: 20.0,
    debtToEquity: 0.4,
    qibSubscription: 140.0,
    niiSubscription: 90.0,
    retailSubscription: 30.0,
gmp: 35,
  },
  {
    id: 'emmvee-photovoltaic',
    companyName: 'Emmvee Photovoltaic Power',
    symbol: 'EMMVEE',
    logoUrl: 'https://picsum.photos/seed/emmvee/100/100',
    market: 'NSE',
    ipoDate: '2024-11-18',
    priceRange: [220, 230],
    sharesOffered: 50000000,
    dealSize: 11250000000,
    description: 'A prominent manufacturer of solar water heating systems and solar photovoltaic modules.',
    industry: 'Renewable Energy',
    predictionScore: 72,
    successProbability: 80,
    expectedReturn: 25.5,
    naturalLanguageExplanation: "Favorable government incentives in the renewable sector and rising energy demand are major tailwinds for Emmvee. The key risks hinge on volatile raw material costs and increasing competition from cheaper imports.",
    shapExplanations: {
      'Government Incentives': 0.3,
      'Rising Energy Demand': 0.25,
      'Raw Material Costs': -0.2,
      'Competition from Imports': -0.1,
      'Strong Order Book': 0.15,
    },
    promoterHoldingPost: 70,
    revenueTtm: 15000000000,
    profitMargin: 8.0,
    roe: 18.5,
    debtToEquity: 0.8,
    qibSubscription: 110.0,
    niiSubscription: 70.0,
    retailSubscription: 25.0,
    gmp: 28,
  },
  {
    id: 'sudeep-pharma',
    companyName: 'Sudeep Pharma',
    symbol: 'SUDEEP',
    logoUrl: 'https://picsum.photos/seed/sudeep/100/100',
    market: 'BSE',
    ipoDate: '2024-12-09',
    priceRange: [300, 315],
    sharesOffered: 15000000,
    dealSize: 4612500000,
    description: 'A specialized manufacturer of mineral-based excipients for the pharmaceutical industry.',
    industry: 'Pharmaceuticals',
    predictionScore: 68,
    successProbability: 75,
    expectedReturn: 18.0,
    naturalLanguageExplanation: "Sudeep Pharma's outlook is supported by its niche market position and consistent financial performance. The main risks to consider are its dependency on a few key clients and the stringent regulatory environment.",
    shapExplanations: {
      'Niche Market Position': 0.3,
      'Strong Client Relationships': 0.2,
      'Regulatory Compliance': -0.15,
      'Dependency on Key Clients': -0.1,
      'Consistent Financials': 0.15,
    },
    promoterHoldingPost: 75,
    revenueTtm: 7000000000,
    profitMargin: 18.0,
    roe: 22.0,
    debtToEquity: 0.5,
    qibSubscription: 95.0,
    niiSubscription: 60.0,
    retailSubscription: 20.0,
    gmp: 22,
  },
  {
    id: 'tenneco-clean-air',
    companyName: 'Tenneco Clean Air India',
    symbol: 'TENNECO',
    logoUrl: 'https://picsum.photos/seed/tenneco/100/100',
    market: 'NSE',
    ipoDate: '2025-01-10',
    priceRange: [600, 625],
    sharesOffered: 12000000,
    dealSize: 7350000000,
    description: 'A leading manufacturer and supplier of clean air solutions for the automotive industry, focusing on emission control systems.',
    industry: 'Automotive Components',
    predictionScore: 75,
    successProbability: 82,
    expectedReturn: 20.0,
    naturalLanguageExplanation: "Tenneco's prospects are strongly tied to the implementation of stricter emission norms and its established brand. However, the cyclical nature of the auto industry and the long-term transition to EVs are factors to watch.",
    shapExplanations: {
      'Stricter Emission Norms': 0.35,
      'Strong OEM Relationships': 0.25,
      'Cyclical Auto Industry': -0.15,
      'EV Transition Risk': -0.1,
      'Established Brand': 0.2,
    },
    promoterHoldingPost: 55,
    revenueTtm: 20000000000,
    profitMargin: 9.5,
    roe: 19.5,
    debtToEquity: 0.6,
    qibSubscription: 120.0,
    niiSubscription: 80.0,
    retailSubscription: 40.0,
    gmp: 25,
  },
  {
    id: 'excelsoft-technologies',
    companyName: 'Excelsoft Technologies',
    symbol: 'EXCELSOFT',
    logoUrl: 'https://picsum.photos/seed/excelsoft/100/100',
    market: 'BSE',
    ipoDate: '2025-01-20',
    priceRange: [150, 160],
    sharesOffered: 20000000,
    dealSize: 3100000000,
    description: 'A provider of technology-based solutions for the education and training sectors.',
    industry: 'Ed-Tech',
    predictionScore: 65,
    successProbability: 70,
    expectedReturn: 15.0,
    naturalLanguageExplanation: 'Growth in digital learning and a diverse product portfolio are positive signals for Excelsoft. The score is tempered by intense competition and relatively low profit margins common in the sector.',
    shapExplanations: {
      'Growing Digital Learning': 0.3,
      'Diverse Product Portfolio': 0.2,
      'Intense Competition': -0.2,
      'Low Margin Business': -0.1,
      'Experienced Management': 0.1,
    },
    promoterHoldingPost: 68,
    revenueTtm: 3000000000,
    profitMargin: 7.0,
    roe: 15.0,
    debtToEquity: 0.3,
    qibSubscription: 80.0,
    niiSubscription: 50.0,
    retailSubscription: 15.0,
    gmp: 18,
  },
  {
    id: 'fujiyama-power-systems',
    companyName: 'Fujiyama Power Systems',
    symbol: 'FUJIYAMA',
    logoUrl: 'https://picsum.photos/seed/fujiyama/100/100',
    market: 'NSE',
    ipoDate: '2025-02-05',
    priceRange: [180, 190],
    sharesOffered: 10000000,
    dealSize: 1850000000,
    description: 'A company engaged in manufacturing and marketing of batteries for various applications including solar and electric vehicles.',
    industry: 'Electrical Equipment',
    predictionScore: 62,
    successProbability: 68,
    expectedReturn: 12.0,
    naturalLanguageExplanation: 'Fujiyama is well-positioned to benefit from growth in the EV and solar sectors. However, the risk of technology obsolescence and raw material price volatility are significant concerns that temper the outlook.',
    shapExplanations: {
      'EV and Solar Growth': 0.35,
      'Make in India Initiative': 0.2,
      'Technology Obsolescence': -0.25,
      'Price Volatility': -0.15,
      'Distribution Network': 0.1,
    },
    promoterHoldingPost: 72,
    revenueTtm: 2500000000,
    profitMargin: 6.5,
    roe: 14.0,
    debtToEquity: 0.9,
    qibSubscription: 70.0,
    niiSubscription: 45.0,
    retailSubscription: 22.0,
    gmp: 15,
  },
   {
    id: 'ola-electric',
    companyName: 'Ola Electric',
    symbol: 'OLAELECT',
    logoUrl: 'https://picsum.photos/seed/ola/100/100',
    market: 'NSE',
    ipoDate: '2025-02-15',
    priceRange: [1200, 1250],
    sharesOffered: 50000000,
    dealSize: 61250000000,
    description: 'A leading electric vehicle company in India, known for its electric scooters and ambitions in battery technology.',
    industry: 'Automotive (EV)',
    predictionScore: 88,
    successProbability: 92,
    expectedReturn: 55.0,
    naturalLanguageExplanation: "Ola Electric's dominant market leadership and strong brand are powerful drivers for its high score. The primary risks are its significant cash burn rate and potential supply chain disruptions, which are common in the fast-growing EV industry.",
    shapExplanations: {
      'Market Leadership in EV': 0.45,
      'Strong Brand Following': 0.3,
      'High Cash Burn Rate': -0.2,
      'Supply Chain Risks': -0.1,
      'Vertical Integration (Battery)': 0.25,
    },
    promoterHoldingPost: 45,
    revenueTtm: 27000000000,
    profitMargin: -25.0, // Still loss-making
    roe: -40.0,
    debtToEquity: 1.5,
    qibSubscription: 250.0,
    niiSubscription: 200.0,
    retailSubscription: 80.0,
    gmp: 60,
  },
  {
    id: 'swiggy',
    companyName: 'Swiggy',
    symbol: 'SWIGGY',
    logoUrl: 'https://picsum.photos/seed/swiggy/100/100',
    market: 'BSE',
    ipoDate: '2025-03-01',
    priceRange: [750, 800],
    sharesOffered: 80000000,
    dealSize: 62000000000,
    description: 'A dominant player in Indias food delivery and quick commerce space, offering a wide range of services from restaurants to grocery delivery.',
    industry: 'Consumer Tech / Logistics',
    predictionScore: 82,
    successProbability: 88,
    expectedReturn: 35.0,
    naturalLanguageExplanation: "Swiggy's strong position in a duopoly market and its successful diversification into quick commerce are major strengths. The company's path to profitability remains a key concern for investors, alongside intense competition.",
    shapExplanations: {
      'Market Duopoly': 0.4,
      'Diversified Services': 0.3,
      'Path to Profitability': -0.15,
      'Intense Competition': -0.1,
      'User Base Growth': 0.2,
    },
    promoterHoldingPost: 40,
    revenueTtm: 85000000000,
    profitMargin: -10.0,
    roe: -30.0,
    debtToEquity: 0.7,
    qibSubscription: 180.0,
    niiSubscription: 150.0,
    retailSubscription: 60.0,
    gmp: 45,
  },
  {
    id: 'firstcry',
    companyName: 'FirstCry',
    symbol: 'FIRSTCRY',
    logoUrl: 'https://picsum.photos/seed/firstcry/100/100',
    market: 'NSE',
    ipoDate: '2025-03-20',
    priceRange: [500, 525],
    sharesOffered: 35000000,
    dealSize: 18000000000,
    description: 'Indias largest omnichannel platform for maternity, baby, and kids products, with a strong online and offline presence.',
    industry: 'E-commerce / Retail',
    predictionScore: 76,
    successProbability: 80,
    expectedReturn: 22.0,
    naturalLanguageExplanation: 'FirstCry benefits greatly from its unique omnichannel strategy and strong brand loyalty in a niche market. The model sees some risk associated with complex inventory management and the mixed post-IPO performance of similar e-commerce peers.',
    shapExplanations: {
      'Omnichannel Strategy': 0.35,
      'Market Leadership': 0.25,
      'Complex Inventory': -0.1,
      'Post-IPO Performance of Peers': -0.05,
      'Brand Loyalty': 0.2,
    },
    promoterHoldingPost: 50,
    revenueTtm: 56000000000,
    profitMargin: 2.5,
    roe: 10.0,
    debtToEquity: 0.4,
    qibSubscription: 110.0,
    niiSubscription: 85.0,
    retailSubscription: 35.0,
    gmp: 30,
  }
];
